language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
services:
  - mongodb
before_install:
 - npm install istanbul -g
 - npm install coveralls -g
 - npm install grunt-cli -g
 - npm install
after_script: "cat ./coverage/lcov.info | coveralls"